name: Sync Google Sheet accepted submissions to JSON files
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch accepted songs
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_SHEET_WORKSHEET_NAME: ${{ secrets.GOOGLE_SHEET_WORKSHEET_NAME }}
        run: |
          python scripts/sheet_sync.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Sync accepted songs from Google Sheet"
          add: "frontend/src/data/*.json frontend/src/utils/songManifest.ts"
          push: true
          branch: frontend-mockup
