name: Sync, Build & Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches: [frontend-mockup]
    paths:
      - "frontend/src/data/**"
      - "frontend/src/utils/songManifest.ts"
      - "frontend/public/pdfs/**"
      - "frontend/package.json"
      - "frontend/vite.config.ts"
      - "frontend/src/**"
      - "frontend/scripts/sheet_sync.py"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  sync-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch accepted songs
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_SHEET_WORKSHEET_NAME: ${{ secrets.GOOGLE_SHEET_WORKSHEET_NAME }}
        run: |
          python scripts/sheet_sync.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Sync accepted songs from Google Sheet"
          add: "frontend/src/data/*.json frontend/src/utils/songManifest.ts"
          push: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
        working-directory: frontend

      - run: npm run build
        working-directory: frontend

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
          publish_branch: gh-pages
