name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [frontend-mockup]
    paths:
      - "frontend/src/data/**"
      - "frontend/src/utils/songManifest.ts"
      - "frontend/public/pdfs/**"
      - "frontend/package.json"
      - "frontend/vite.config.ts"
      - "frontend/src/**"
      - "frontend/scripts/sheet_sync.py"
      - ".github/workflows/deploy.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
          publish_branch: gh-pages
